spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
     username: root
    password: ys1234
    url: jdbc:mysql://localhost:3306/book?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /bookSystem
